#![forbid(unsafe_code)]

use crate::scaffold::entity::{EntitySpec, FieldSpec};

pub fn render_cargo_toml(name: &str) -> String {
    format!(
        r#"[package]
name = "{name}"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
ember-core = "0.1.0"
ember-macros = "0.1.0"
ember-logging = "0.1.0"
serde = {{ version = "1", features = ["derive"] }}
serde_json = "1"
"#
    )
}

pub fn render_config_rs() -> String {
    r#"#![forbid(unsafe_code)]

use serde::Deserialize;

#[derive(Debug, Clone, Deserialize)]
pub struct AppConfig {
    pub service_name: String,
    pub listen_addr: String,
}
"#
    .to_string()
}

pub fn render_readme(name: &str) -> String {
    format!(
        r#"# {name}

An Ember service generated by `ember new`.

## Run

```bash
cargo run
```

Then open:
- `http://localhost:8080/health`
"#
    )
}

pub fn render_application_yaml(name: &str) -> String {
    format!(
        r#"service_name: "{name}"
listen_addr: "0.0.0.0:8080"

db:
  url: "postgres://localhost:5432/{name}"
  username: "postgres"
  password: "postgres"
"#
    )
}

pub fn render_main_rs(entities: &[EntitySpec]) -> String {
    let mut imports = String::from(
        "use anyhow::Result;\nuse controllers::health_controller::HealthController;\nuse ember_logging::{init as init_logging, log_startup};\nuse services::system_info_service::SystemInfoService;\n",
    );

    for entity in entities {
        let snake = entity.snake_name();
        imports.push_str(&format!(
            "use controllers::{snake}_controller::{}Controller;\n",
            entity.name
        ));
        imports.push_str(&format!(
            "use services::{snake}_service::{}Service;\n",
            entity.name
        ));
    }

    let mut controller_inits = String::new();
    for entity in entities {
        let snake = entity.snake_name();
        controller_inits.push_str(&format!(
            "    let {snake}_service = {}Service::new();\n",
            entity.name
        ));
        controller_inits.push_str(&format!(
            "    let {snake}_controller = {}Controller::new({snake}_service);\n",
            entity.name
        ));
        controller_inits.push_str(&format!(
            "    app.register_controller({snake}_controller);\n"
        ));
    }

    format!(
        r#"#![forbid(unsafe_code)]

mod config;
mod controllers;
mod domain;
mod mappers;
mod repository;
mod services;

{imports}

fn main() -> Result<()> {{
    init_logging().map_err(anyhow::Error::new)?;

    let system_info = SystemInfoService::default();
    let controller = HealthController::new(system_info);

    let mut app = ember_core::App::new();
    app.register_controller(controller);
{controller_inits}
    log_startup("ember-service", "ember-runtime");
    app.run().map_err(anyhow::Error::new)?;

    Ok(())
}}
"#
    )
}

pub fn render_controllers_mod(entities: &[EntitySpec]) -> String {
    let mut out = String::from("pub mod dto;\npub mod health_controller;\n");
    for entity in entities {
        out.push_str(&format!("pub mod {}_controller;\n", entity.snake_name()));
    }
    out
}

pub fn render_controller_dto(entities: &[EntitySpec]) -> String {
    let mut out = String::from(
        "#![forbid(unsafe_code)]\n\nuse serde::{Deserialize, Serialize};\n\n",
    );

    for entity in entities {
        let response_name = format!("{}Response", entity.name);
        let create_name = format!("Create{}Request", entity.name);
        let update_name = format!("Update{}Request", entity.name);

        out.push_str(&format!("#[derive(Debug, Serialize)]\npub struct {response_name} {{\n"));
        out.push_str(&render_fields(&entity.fields, true, false));
        out.push_str("}\n\n");

        out.push_str(&format!("#[derive(Debug, Deserialize)]\npub struct {create_name} {{\n"));
        out.push_str(&render_fields(&entity.fields, false, false));
        out.push_str("}\n\n");

        out.push_str(&format!("#[derive(Debug, Deserialize)]\npub struct {update_name} {{\n"));
        out.push_str(&render_fields(&entity.fields, false, true));
        out.push_str("}\n\n");
    }

    if entities.is_empty() {
        out.push_str("#[derive(Debug, Serialize)]\npub struct MessageResponse {\n    pub message: String,\n}\n");
    }

    out
}

pub fn render_domain_mod(entities: &[EntitySpec]) -> String {
    let mut out = String::new();
    for entity in entities {
        out.push_str(&format!("pub mod {};\n", entity.snake_name()));
    }
    if out.is_empty() {
        out.push_str("// domain modules\n");
    }
    out
}

pub fn render_domain_entity(entity: &EntitySpec) -> String {
    let id_ty = &entity.id_field().ty;
    let name = &entity.name;
    let mut out = String::from("#![forbid(unsafe_code)]\n\n");
    out.push_str(&format!("pub type {name}Id = {id_ty};\n\n"));
    out.push_str(&format!("#[derive(Debug, Clone)]\npub struct {name} {{\n"));
    out.push_str(&render_fields(&entity.fields, true, false));
    out.push_str("}\n\n");
    out.push_str(&format!("#[derive(Debug, Clone)]\npub struct New{name} {{\n"));
    out.push_str(&render_fields(&entity.fields, false, false));
    out.push_str("}\n\n");
    out.push_str(&format!("#[derive(Debug, Clone)]\npub struct {name}Update {{\n"));
    out.push_str(&format!("    pub id: {name}Id,\n"));
    out.push_str(&render_fields(&entity.fields, false, true));
    out.push_str("}\n");
    out
}

pub fn render_mappers_mod(entities: &[EntitySpec]) -> String {
    let mut out = String::from("pub mod controller_mapper;\npub mod repository_mapper;\n");
    if entities.is_empty() {
        out.push_str("// add mapper modules as needed\n");
    }
    out
}

pub fn render_controller_mapper(entities: &[EntitySpec]) -> String {
    let mut out = String::from("#![forbid(unsafe_code)]\n\n");
    for entity in entities {
        let snake = entity.snake_name();
        let name = &entity.name;
        out.push_str(&format!(
            "use crate::controllers::dto::{{Create{name}Request, Update{name}Request, {name}Response}};\n"
        ));
        out.push_str(&format!(
            "use crate::domain::{snake}::{{{name}, New{name}, {name}Update, {name}Id}};\n\n"
        ));

        out.push_str(&format!(
            "pub fn to_{snake}_response(entity: {name}) -> {name}Response {{\n"
        ));
        out.push_str(&format!("    {name}Response {{\n"));
        out.push_str(&render_field_assignments(&entity.fields, "entity", true));
        out.push_str("    }\n}\n\n");

        out.push_str(&format!(
            "pub fn to_new_{snake}(input: Create{name}Request) -> New{name} {{\n"
        ));
        out.push_str(&format!("    New{name} {{\n"));
        out.push_str(&render_field_assignments(&entity.fields, "input", false));
        out.push_str("    }\n}\n\n");

        out.push_str(&format!(
            "pub fn to_update_{snake}(id: {name}Id, input: Update{name}Request) -> {name}Update {{\n"
        ));
        out.push_str(&format!("    {name}Update {{\n        id,\n"));
        out.push_str(&render_field_assignments(&entity.fields, "input", false));
        out.push_str("    }\n}\n\n");
    }
    if entities.is_empty() {
        out.push_str("// controller mappers\n");
    }
    out
}

pub fn render_repository_mapper(entities: &[EntitySpec]) -> String {
    let mut out = String::from("#![forbid(unsafe_code)]\n\n");
    for entity in entities {
        let snake = entity.snake_name();
        let name = &entity.name;
        out.push_str(&format!(
            "use crate::domain::{snake}::{{{name}, New{name}, {name}Update}};\n"
        ));
        out.push_str(&format!(
            "use crate::repository::entities::{snake}_entity::{{{name}Entity, {name}EntityUpdate}};\n\n"
        ));

        out.push_str(&format!(
            "pub fn entity_to_{snake}(entity: {name}Entity) -> {name} {{\n"
        ));
        out.push_str(&format!("    {name} {{\n"));
        out.push_str(&render_field_assignments(&entity.fields, "entity", true));
        out.push_str("    }\n}\n\n");

        out.push_str(&format!(
            "pub fn new_{snake}_to_entity(input: New{name}) -> {name}Entity {{\n"
        ));
        out.push_str(&format!("    {name}Entity {{\n"));
        out.push_str(&render_field_assignments(&entity.fields, "input", false));
        out.push_str("    }\n}\n\n");

        out.push_str(&format!(
            "pub fn update_{snake}_to_entity(input: {name}Update) -> {name}EntityUpdate {{\n"
        ));
        out.push_str(&format!("    {name}EntityUpdate {{\n"));
        out.push_str(&render_field_assignments(&entity.fields, "input", true));
        out.push_str("    }\n}\n\n");
    }
    if entities.is_empty() {
        out.push_str("// repository mappers\n");
    }
    out
}

pub fn render_repository_mod(entities: &[EntitySpec]) -> String {
    let mut out = String::from("pub mod entities;\npub mod repositories;\n");
    if entities.is_empty() {
        out.push_str("// repository modules\n");
    }
    out
}

pub fn render_repository_entities_mod(entities: &[EntitySpec]) -> String {
    let mut out = String::new();
    for entity in entities {
        out.push_str(&format!("pub mod {}_entity;\n", entity.snake_name()));
    }
    if out.is_empty() {
        out.push_str("// entity modules\n");
    }
    out
}

pub fn render_repository_entity(entity: &EntitySpec) -> String {
    let name = &entity.name;
    let id_ty = format!("{}Id", name);
    let mut out = String::from("#![forbid(unsafe_code)]\n\n");
    out.push_str(&format!("use crate::domain::{}::{id_ty};\n\n", entity.snake_name()));
    out.push_str(&format!("#[derive(Debug, Clone)]\npub struct {name}Entity {{\n"));
    out.push_str(&render_fields(&entity.fields, true, false));
    out.push_str("}\n\n");
    out.push_str(&format!("#[derive(Debug, Clone)]\npub struct {name}EntityUpdate {{\n"));
    out.push_str(&format!("    pub id: {id_ty},\n"));
    out.push_str(&render_fields(&entity.fields, false, true));
    out.push_str("}\n");
    out
}

pub fn render_repository_repositories_mod(entities: &[EntitySpec]) -> String {
    let mut out = String::new();
    for entity in entities {
        out.push_str(&format!("pub mod {}_repository;\n", entity.snake_name()));
    }
    if out.is_empty() {
        out.push_str("// repository modules\n");
    }
    out
}

pub fn render_repository_repository(entity: &EntitySpec) -> String {
    let name = &entity.name;
    let snake = entity.snake_name();
    let id_ty = format!("{}Id", name);
    let mut out = String::from("#![forbid(unsafe_code)]\n\n");
    out.push_str(&format!("use std::sync::{{Arc, Mutex, MutexGuard}};\n\n"));
    out.push_str(&format!("use crate::domain::{snake}::{id_ty};\n"));
    out.push_str(&format!(
        "use crate::repository::entities::{snake}_entity::{{{name}Entity, {name}EntityUpdate}};\n\n"
    ));
    out.push_str("#[derive(Debug, Default)]\nstruct Store {\n    next_id: ");
    out.push_str(&id_ty);
    out.push_str(",\n    items: Vec<");
    out.push_str(&format!("{name}Entity"));
    out.push_str(">,\n}\n\n");
    out.push_str(&format!(
        "#[derive(Clone, Default)]\npub struct {name}Repository {{\n    state: Arc<Mutex<Store>>,\n}}\n\n"
    ));
    out.push_str(&format!("impl {name}Repository {{\n"));
    out.push_str("    pub fn new() -> Self {\n        Self { state: Arc::new(Mutex::new(Store { next_id: 1, items: Vec::new() })) }\n    }\n\n");
    out.push_str(&format!(
        "    pub fn list_all(&self) -> Vec<{name}Entity> {{\n        let store = self.lock_store();\n        store.items.clone()\n    }}\n\n"
    ));
    out.push_str(&format!(
        "    pub fn find_by_id(&self, id: {id_ty}) -> Option<{name}Entity> {{\n        let store = self.lock_store();\n        store.items.iter().find(|item| item.id == id).cloned()\n    }}\n\n"
    ));
    out.push_str(&format!(
        "    pub fn save(&self, mut entity: {name}Entity) -> {name}Entity {{\n        let mut store = self.lock_store_mut();\n        if entity.id == 0 {{ entity.id = store.next_id; store.next_id = store.next_id.saturating_add(1); }}\n        store.items.push(entity.clone());\n        entity\n    }}\n\n"
    ));
    out.push_str(&format!(
        "    pub fn update(&self, update: {name}EntityUpdate) -> Option<{name}Entity> {{\n        let mut store = self.lock_store_mut();\n        let Some(item) = store.items.iter_mut().find(|item| item.id == update.id) else {{ return None; }};\n"
    ));
    for field in entity.fields.iter().filter(|f| f.name != "id") {
        out.push_str(&format!("        if let Some(value) = update.{} {{ item.{} = value; }}\n", field.name, field.name));
    }
    out.push_str("        Some(item.clone())\n    }\n\n");
    out.push_str(&format!(
        "    pub fn delete_by_id(&self, id: {id_ty}) -> bool {{\n        let mut store = self.lock_store_mut();\n        let before = store.items.len();\n        store.items.retain(|item| item.id != id);\n        before != store.items.len()\n    }}\n\n"
    ));
    out.push_str("    fn lock_store(&self) -> MutexGuard<'_, Store> {\n        self.state.lock().unwrap_or_else(|poisoned| poisoned.into_inner())\n    }\n\n    fn lock_store_mut(&self) -> MutexGuard<'_, Store> {\n        self.state.lock().unwrap_or_else(|poisoned| poisoned.into_inner())\n    }\n}\n");
    out
}

pub fn render_services_mod(entities: &[EntitySpec]) -> String {
    let mut out = String::from("pub mod system_info_service;\n");
    for entity in entities {
        out.push_str(&format!("pub mod {}_service;\n", entity.snake_name()));
    }
    if entities.is_empty() {
        out.push_str("// service modules\n");
    }
    out
}

pub fn render_health_controller() -> String {
    r#"#![forbid(unsafe_code)]

use crate::services::system_info_service::SystemInfoService;
use ember_core::Json;
use ember_macros::{controller, get};
use serde::Serialize;

#[derive(Debug, Serialize)]
pub struct HealthResponse {
    pub status: String,
    pub system: String,
}

pub struct HealthController {
    system_info: SystemInfoService,
}

impl HealthController {
    pub fn new(system_info: SystemInfoService) -> Self {
        Self { system_info }
    }
}

#[controller]
impl HealthController {
    #[get("/health")]
    pub fn health(&self) -> Json<HealthResponse> {
        Json(HealthResponse {
            status: "ok".to_owned(),
            system: self.system_info.status(),
        })
    }
}
"#
    .to_string()
}

pub fn render_service(entity: &EntitySpec) -> String {
    let name = &entity.name;
    let snake = entity.snake_name();
    format!(
        r#"#![forbid(unsafe_code)]

use crate::domain::{snake}::{{{name}, New{name}, {name}Update, {name}Id}};
use crate::mappers::repository_mapper;
use crate::repository::repositories::{snake}_repository::{name}Repository;

#[derive(Debug, Clone, Default)]
pub struct {name}Service {{
    repository: {name}Repository,
}}

impl {name}Service {{
    pub fn new() -> Self {{
        Self {{
            repository: {name}Repository::new(),
        }}
    }}

    pub fn list_{snake}s(&self) -> Vec<{name}> {{
        self.repository
            .list_all()
            .into_iter()
            .map(repository_mapper::entity_to_{snake})
            .collect()
    }}

    pub fn get_{snake}(&self, id: {name}Id) -> Option<{name}> {{
        self.repository
            .find_by_id(id)
            .map(repository_mapper::entity_to_{snake})
    }}

    pub fn add_{snake}(&self, input: New{name}) -> {name} {{
        let entity = repository_mapper::new_{snake}_to_entity(input);
        let saved = self.repository.save(entity);
        repository_mapper::entity_to_{snake}(saved)
    }}

    pub fn update_{snake}(&self, update: {name}Update) -> Option<{name}> {{
        self.repository
            .update(repository_mapper::update_{snake}_to_entity(update))
            .map(repository_mapper::entity_to_{snake})
    }}

    pub fn remove_{snake}(&self, id: {name}Id) -> bool {{
        self.repository.delete_by_id(id)
    }}
}}
"#
    )
}

pub fn render_controller(entity: &EntitySpec) -> String {
    let name = &entity.name;
    let snake = entity.snake_name();
    let plural = entity.plural_snake_name();
    format!(
        r#"#![forbid(unsafe_code)]

use ember_core::Json;
use ember_macros::{{controller, delete, get, post, put}};

use crate::controllers::dto::{{Create{name}Request, Update{name}Request, {name}Response}};
use crate::domain::{snake}::{name}Id;
use crate::mappers::controller_mapper;
use crate::services::{snake}_service::{name}Service;

#[derive(Clone)]
pub struct {name}Controller {{
    service: {name}Service,
}}

impl {name}Controller {{
    pub fn new(service: {name}Service) -> Self {{
        Self {{ service }}
    }}
}}

#[controller]
impl {name}Controller {{
    #[get("/{plural}")]
    pub fn list_{plural}(&self) -> Json<Vec<{name}Response>> {{
        let items = self.service.list_{snake}s();
        Json(items.into_iter().map(controller_mapper::to_{snake}_response).collect())
    }}

    #[get("/{plural}/{{id}}")]    
    pub fn get_{snake}(&self, id: {name}Id) -> Json<Option<{name}Response>> {{
        let item = self
            .service
            .get_{snake}(id)
            .map(controller_mapper::to_{snake}_response);
        Json(item)
    }}

    #[post("/{plural}")]
    pub fn add_{snake}(&self, input: Create{name}Request) -> Json<{name}Response> {{
        let item = self.service.add_{snake}(controller_mapper::to_new_{snake}(input));
        Json(controller_mapper::to_{snake}_response(item))
    }}

    #[put("/{plural}/{{id}}")]
    pub fn update_{snake}(&self, id: {name}Id, update: Update{name}Request) -> Json<Option<{name}Response>> {{
        let item = self
            .service
            .update_{snake}(controller_mapper::to_update_{snake}(id, update))
            .map(controller_mapper::to_{snake}_response);
        Json(item)
    }}

    #[delete("/{plural}/{{id}}")]
    pub fn remove_{snake}(&self, id: {name}Id) -> Json<bool> {{
        Json(self.service.remove_{snake}(id))
    }}
}}
"#
    )
}

pub fn render_system_info_service() -> String {
    r#"#![forbid(unsafe_code)]

#[derive(Debug, Clone, Default)]
pub struct SystemInfoService;

impl SystemInfoService {
    pub fn status(&self) -> String {
        "ok".to_owned()
    }
}
"#
    .to_string()
}

fn render_fields(fields: &[FieldSpec], include_id: bool, optional: bool) -> String {
    let mut out = String::new();
    for field in fields {
        if !include_id && field.name == "id" {
            continue;
        }
        let ty = if optional {
            wrap_option(&field.ty)
        } else {
            field.ty.clone()
        };
        out.push_str(&format!("    pub {}: {},\n", field.name, ty));
    }
    out
}

fn render_field_assignments(fields: &[FieldSpec], source: &str, include_id: bool) -> String {
    let mut out = String::new();
    for field in fields {
        if !include_id && field.name == "id" {
            continue;
        }
        out.push_str(&format!("        {}: {}.{},\n", field.name, source, field.name));
    }
    out
}

fn wrap_option(ty: &str) -> String {
    if ty.trim_start().starts_with("Option<") {
        ty.to_string()
    } else {
        format!("Option<{ty}>")
    }
}
